export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST'
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS'
export const MOVIE_LIST_FAIL = 'MOVIE_LIST_FAIL'
export const MOVIE_LIST_REMOVE = 'MOVIE_LIST_REMOVE'

export const CHARACTER_LIST_REQUEST = 'CHARACTER_LIST_REQUEST'
export const CHARACTER_LIST_SUCCESS = 'CHARACTER_LIST_SUCCESS'
export const CHARACTER_LIST_FAIL = 'CHARACTER_LIST_FAIL'
export const CHARACTER_LIST_REMOVE = 'CHARACTER_LIST_REMOVE'