export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST'
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS'
export const MOVIE_LIST_FAIL = 'MOVIE_LIST_FAIL'
export const MOVIE_LIST_REMOVE = 'MOVIE_LIST_REMOVE'

export const PEOPLE_LIST_REQUEST = 'PEOPLE_LIST_REQUEST'
export const PEOPLE_LIST_SUCCESS = 'PEOPLE_LIST_SUCCESS'
export const PEOPLE_LIST_FAIL = 'PEOPLE_LIST_FAIL'
export const PEOPLE_LIST_REMOVE = 'PEOPLE_LIST_REMOVE'